version: '3.8'

services:
  proxy:
    container_name: noti-proxy
    image: nginx:latest
    depends_on:
      - mysqldb
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certbot/conf:/etc/nginx/ssl
      - ./proxy/certbot/data:/var/www/certbot
  certbot:
    container_name: noti-certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email event.42seoul@gmail.com --agree-tos --no-eff-email -d noti.42cadet.kr
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/logs:/var/log/letsencrypt
      - ./proxy/certbot/data:/var/www/certbot
  mysqldb:
    container_name: noti-mysql
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: noti-api
    depends_on:
      - mysqldb
    build: ./src
    image: noti-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_PORT=$MYSQLDB_DOCKER_PORT
      - DATABASE_HOST=noti-mysql
      - DATABASE_USERNAME=$MYSQLDB_USER
      - DATABASE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DATABASE_NAME=$MYSQLDB_DATABASE
      - BACK_PORT=$NODE_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
